name: Build and Push Agent to ECR

on:
  push:
    branches:
      - main

jobs:
  build-push-image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR Public
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_IMAGE_URI: public.ecr.aws/z3s6d3y0/terraguardian-agent:latest
        run: |
          docker build -t $ECR_IMAGE_URI ./agent
          docker push $ECR_IMAGE_URI
